[package]
name = "blst-deno"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bls-signatures = "0.15.0"
bls12_381 = "0.8.0"
deno_bindgen = "0.8.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
